name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - anaconda-anon-usage=0.4.4
  - anyio=4.11.0
  - archspec=0.2.3
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.5
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.9.9
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.8.3
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - comm=0.2.3
  - conda=24.11.3
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.7.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - cpython=3.12.11
  - cryptography=42.0.5
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distro=1.9.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.6.2
  - fmt=9.1.0
  - fqdn=1.5.1
  - frozendict=2.4.2
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - krb5=1.20.1
  - lark=1.3.0
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libcurl=8.7.1
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsolv=0.7.24
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libxml2=2.13.1
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - menuinst=2.1.2
  - mistune=3.1.4
  - nb_conda_kernels=2.5.2
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - openssl=3.5.3
  - overrides=7.7.0
  - packaging=24.1
  - pandoc=3.8
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.12.11
  - python-json-logger=2.0.7
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - readline=8.2
  - referencing=0.36.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.27.1
  - ruamel.yaml=0.17.21
  - send2trash=1.8.3
  - setuptools=72.1.0
  - sniffio=1.3.1
  - soupsieve=2.8
  - sqlite=3.45.3
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - truststore=0.8.0
  - types-python-dateutil=2.9.0.20250822
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - uri-template=1.3.0
  - urllib3=2.2.2
  - voila=0.5.11
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - flatbuffers==24.3.25
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.66.2
      - h5py==3.12.1
      - keras==3.6.0
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.1
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - namex==0.0.8
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.3.4.1
      - nvidia-cuda-cupti-cu12==12.3.101
      - nvidia-cuda-nvcc-cu12==12.3.107
      - nvidia-cuda-nvrtc-cu12==12.3.107
      - nvidia-cuda-runtime-cu12==12.3.101
      - nvidia-cudnn-cu12==8.9.7.29
      - nvidia-cufft-cu12==11.0.12.1
      - nvidia-curand-cu12==10.3.4.107
      - nvidia-cusolver-cu12==11.5.4.101
      - nvidia-cusparse-cu12==12.2.0.103
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - opt-einsum==3.4.0
      - optree==0.13.0
      - pygments==2.18.0
      - rich==13.9.2
      - six==1.16.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - typing-extensions==4.12.2
      - werkzeug==3.0.4
      - wrapt==1.16.0
